#!/usr/bin/env python3
"""
scripts/run_calibration.py — OptiTrack ↔ World Frame Calibration Tool

Computes the rigid transform from OptiTrack coordinates to your desired
world frame (e.g., robot base frame) using the V120:Trio's triangular
3-ball calibration frame.

Two Calibration Modes
---------------------

MODE 1: 3-Point Frame Definition (default, --mode frame)
    Uses exactly 3 placements of the triangular calibration frame to
    define the world coordinate system directly:

        Placement 1 = ORIGIN
            Place the calibration frame at the point you want as (0, 0, 0)
            in your world frame — typically the robot base or a table corner.

        Placement 2 = X-AXIS direction
            Place it along the direction you want as +X.
            Only the direction matters, not the distance.

        Placement 3 = XY-PLANE point
            Place it somewhere in the XY plane (not on the X axis).
            This defines which way +Y points. Z = X × Y (right-hand rule).

    The script computes:
        X_axis = normalize(point2 - point1)
        Z_axis = normalize(X_axis × (point3 - point1))
        Y_axis = Z_axis × X_axis
        Origin = point1

    This gives an exact frame — no least-squares fitting needed.

MODE 2: Multi-Point SVD Registration (--mode svd)
    The original N-point approach. Place the calibration frame at N ≥ 3
    known positions, manually enter the target coordinates for each,
    and compute the best-fit rigid transform via SVD (Arun's method).
    Use this when you have measured reference positions (e.g., from the
    robot's known end-effector coordinates).

Usage
-----
    cd vision_engine

    # 3-point frame definition (recommended for initial setup):
    python scripts/run_calibration.py

    # With a specific table height (if origin is on the table):
    python scripts/run_calibration.py --table-height 0.72

    # SVD mode with manual coordinate entry:
    python scripts/run_calibration.py --mode svd

    # Specify which rigid body to track:
    python scripts/run_calibration.py --body calibration_triangle

Output
------
    config/calibration.yaml — 4×4 homogeneous transform matrix
"""

import sys
import os
import time
import argparse
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import yaml
from cv.optitrack_client import OptiTrackClient
from cv.transforms import compute_rigid_transform, apply_transform, make_transform


def load_config(config_path: str) -> dict:
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def save_calibration(output_path: str, transform: np.ndarray, method: str, details: dict):
    """Save calibration result to YAML."""
    data = {
        "transform": transform.tolist(),
        "method": method,
        **details,
    }
    with open(output_path, "w") as f:
        f.write("# Auto-generated by run_calibration.py\n")
        f.write(f"# Method: {method}\n")
        if "rms_error" in details:
            f.write(f"# RMS error: {details['rms_error']:.4f} m ({details['rms_error']*1000:.1f} mm)\n")
        f.write(f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        yaml.dump(data, f, default_flow_style=None)
    print(f"\n[Calibration] Saved to {output_path}")


def record_position(client, body_name: str, label: str, num_samples: int = 60) -> np.ndarray:
    """
    Record the averaged position of a rigid body.

    Averages over num_samples frames (~2 seconds at 30Hz) for stability.
    Reports standard deviation as a quality indicator.

    Parameters
    ----------
    client : OptiTrackClient
    body_name : str
    label : str
        Description printed during recording.
    num_samples : int
        Number of frames to average.

    Returns
    -------
    position : np.ndarray, shape (3,)
        Averaged position in OptiTrack Z-up frame.
    """
    input(f"\n  Place the calibration frame at: {label}\n"
          f"  Keep it still and visible, then press Enter...")

    readings = []
    print(f"  Recording ({num_samples} frames)...", end="", flush=True)
    for _ in range(num_samples):
        bodies = client.get_rigid_bodies()
        if body_name in bodies and bodies[body_name].tracking_valid:
            readings.append(bodies[body_name].position.copy())
        time.sleep(0.033)
    print(" done.")

    if len(readings) < num_samples // 2:
        print(f"  [WARNING] Only got {len(readings)}/{num_samples} valid readings.")
        print(f"  The calibration frame may be occluded. Try repositioning.")
        if len(readings) < 3:
            raise RuntimeError("Too few valid readings. Cannot proceed.")

    pos = np.mean(readings, axis=0)
    std = np.std(readings, axis=0)
    print(f"  Recorded: ({pos[0]:.4f}, {pos[1]:.4f}, {pos[2]:.4f}) m")
    print(f"  Std dev:  ({std[0]:.4f}, {std[1]:.4f}, {std[2]:.4f}) m")

    if np.max(std) > 0.002:
        print(f"  [WARNING] High std dev ({np.max(std)*1000:.1f} mm). "
              f"Was the frame moving during recording?")

    return pos


# ──────────────────────────────────────────────────────────────────────────────
# Mode 1: 3-Point Frame Definition
# ──────────────────────────────────────────────────────────────────────────────

def calibrate_3point_frame(client, body_name: str, table_height: float) -> tuple:
    """
    Define the world coordinate frame from 3 placements of the calibration tool.

    The 3 points define:
        Point 1 → Origin of the world frame
        Point 2 → Direction of the +X axis
        Point 3 → A point in the XY plane (determines +Y direction)

    Z axis is computed via right-hand rule: Z = X × Y_temp, then Y = Z × X.

    The resulting transform maps OptiTrack coordinates → the new world frame.

    Parameters
    ----------
    client : OptiTrackClient
    body_name : str
    table_height : float
        If > 0, the origin's Z coordinate is overridden to this value.
        Useful when the origin is on the table surface at a known height.

    Returns
    -------
    T : np.ndarray, shape (4, 4)
        Transform from OptiTrack frame to world frame.
    details : dict
        Calibration metadata.
    """
    print("""
╔══════════════════════════════════════════════════════════════════════╗
║           3-Point Frame Calibration (Triangular Tool)              ║
╠══════════════════════════════════════════════════════════════════════╣
║                                                                     ║
║  You will place the triangular calibration frame at 3 positions:    ║
║                                                                     ║
║    1. ORIGIN   — where you want (0, 0, 0) in your world frame      ║
║                  (e.g., robot base, table corner)                    ║
║                                                                     ║
║    2. +X AXIS  — a point along the desired +X direction             ║
║                  (e.g., straight ahead from robot base)              ║
║                                                                     ║
║    3. XY PLANE — a point in the XY plane, off the X axis            ║
║                  (e.g., to the left of the robot base)               ║
║                  This determines which way +Y points.                ║
║                                                                     ║
║  Z axis is computed automatically (right-hand rule: Z = X × Y).     ║
║  All 3 points should be on the same horizontal surface (table).     ║
║                                                                     ║
║  The calibration frame must be visible to V120:Trio at each step.   ║
╚══════════════════════════════════════════════════════════════════════╝
""")

    # Record 3 positions
    p1 = record_position(client, body_name, "ORIGIN (where you want 0,0,0)")
    p2 = record_position(client, body_name, "+X DIRECTION (along desired X axis)")
    p3 = record_position(client, body_name, "XY PLANE (off the X axis, defines +Y side)")

    # ── Compute frame from 3 points ──
    #
    # X axis: from origin towards point 2
    x_vec = p2 - p1
    x_len = np.linalg.norm(x_vec)
    if x_len < 0.01:
        raise RuntimeError(
            f"Points 1 and 2 are too close ({x_len*1000:.1f} mm apart). "
            f"Place them farther apart for a reliable X axis."
        )
    x_axis = x_vec / x_len

    # Temporary Y direction: from origin towards point 3
    y_temp = p3 - p1
    y_temp_len = np.linalg.norm(y_temp)
    if y_temp_len < 0.01:
        raise RuntimeError(
            f"Points 1 and 3 are too close ({y_temp_len*1000:.1f} mm apart). "
            f"Place them farther apart."
        )

    # Z axis: X × Y_temp (perpendicular to the plane, pointing up)
    z_axis = np.cross(x_axis, y_temp / y_temp_len)
    z_len = np.linalg.norm(z_axis)
    if z_len < 0.01:
        raise RuntimeError(
            "Points are nearly collinear — Z axis cannot be determined. "
            "Point 3 must be off the line between points 1 and 2."
        )
    z_axis = z_axis / z_len

    # Ensure Z points upward (positive Z in Z-up convention)
    if z_axis[2] < 0:
        z_axis = -z_axis
        print("  [Info] Flipped Z axis to point upward.")

    # Final Y axis: Z × X (ensures orthogonality)
    y_axis = np.cross(z_axis, x_axis)
    y_axis = y_axis / np.linalg.norm(y_axis)

    # ── Build the transform ──
    #
    # The rotation matrix R_world has columns [X, Y, Z] in OptiTrack coords.
    # This rotates from world frame to OptiTrack frame.
    # We want OptiTrack → world, so we invert: R = R_world^T
    #
    # The origin in OptiTrack coords is p1.
    # In world coords, the origin is (0, 0, table_height) or (0, 0, 0).

    R_opti_to_world = np.column_stack([x_axis, y_axis, z_axis])  # 3×3

    # The transform T maps a point p_opti to p_world:
    #   p_world = R^T @ (p_opti - origin_opti)
    # Which is:
    #   T = [R^T | -R^T @ origin_opti]
    #       [0   |        1          ]

    R = R_opti_to_world.T  # World-aligned rotation
    origin_opti = p1

    # Translation: we want T @ origin_opti = (0, 0, table_height)
    # So t = target_origin - R @ origin_opti
    target_origin = np.array([0.0, 0.0, table_height])
    t = target_origin - R @ origin_opti

    T = make_transform(R, t)

    # ── Verify ──
    p1_world = apply_transform(T, p1)
    p2_world = apply_transform(T, p2)
    p3_world = apply_transform(T, p3)

    print(f"\n{'='*60}")
    print("3-Point Frame Calibration Result")
    print(f"{'='*60}")
    print(f"\nAxis directions (in OptiTrack frame):")
    print(f"  X axis: ({x_axis[0]:.4f}, {x_axis[1]:.4f}, {x_axis[2]:.4f})")
    print(f"  Y axis: ({y_axis[0]:.4f}, {y_axis[1]:.4f}, {y_axis[2]:.4f})")
    print(f"  Z axis: ({z_axis[0]:.4f}, {z_axis[1]:.4f}, {z_axis[2]:.4f})")
    print(f"\nOrthogonality check:")
    print(f"  X·Y = {np.dot(x_axis, y_axis):.6f} (should be ~0)")
    print(f"  X·Z = {np.dot(x_axis, z_axis):.6f} (should be ~0)")
    print(f"  Y·Z = {np.dot(y_axis, z_axis):.6f} (should be ~0)")
    print(f"  det(R) = {np.linalg.det(R_opti_to_world):.6f} (should be ~1)")

    print(f"\nVerification (transformed to world frame):")
    print(f"  Point 1 (origin):   ({p1_world[0]:.4f}, {p1_world[1]:.4f}, {p1_world[2]:.4f})"
          f"  — should be (0, 0, {table_height:.2f})")
    print(f"  Point 2 (+X dir):   ({p2_world[0]:.4f}, {p2_world[1]:.4f}, {p2_world[2]:.4f})"
          f"  — should have +X, Y≈0, Z≈{table_height:.2f}")
    print(f"  Point 3 (XY plane): ({p3_world[0]:.4f}, {p3_world[1]:.4f}, {p3_world[2]:.4f})"
          f"  — should have Y≠0, Z≈{table_height:.2f}")

    print(f"\nDistances between calibration points:")
    print(f"  Origin → +X point: {x_len*100:.1f} cm")
    print(f"  Origin → XY point: {y_temp_len*100:.1f} cm")

    print(f"\nTransform (4×4):")
    for row in T:
        print(f"  [{row[0]:8.5f}  {row[1]:8.5f}  {row[2]:8.5f}  {row[3]:8.5f}]")

    details = {
        "origin_optitrack": p1.tolist(),
        "x_point_optitrack": p2.tolist(),
        "xy_point_optitrack": p3.tolist(),
        "x_axis_distance_m": float(x_len),
        "xy_axis_distance_m": float(y_temp_len),
        "table_height": float(table_height),
        "orthogonality_xy": float(np.dot(x_axis, y_axis)),
        "orthogonality_xz": float(np.dot(x_axis, z_axis)),
        "orthogonality_yz": float(np.dot(y_axis, z_axis)),
    }

    return T, details


# ──────────────────────────────────────────────────────────────────────────────
# Mode 2: Multi-Point SVD Registration
# ──────────────────────────────────────────────────────────────────────────────

def calibrate_svd(client, body_name: str, min_points: int) -> tuple:
    """
    N-point SVD registration. User enters known world coordinates for each
    placement, then Arun's method computes the best-fit transform.
    """
    print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║              SVD Multi-Point Calibration                            ║
╠══════════════════════════════════════════════════════════════════════╣
║  1. Place the calibration frame at a known position                 ║
║  2. Enter the known (x, y, z) coordinates in meters                ║
║  3. Press Enter to record the OptiTrack reading                     ║
║  4. Repeat for at least {min_points} positions (6-8 recommended)              ║
║  5. Type 'done' when finished                                       ║
╚══════════════════════════════════════════════════════════════════════╝
""")

    optitrack_points = []
    target_points = []

    while True:
        idx = len(optitrack_points) + 1
        print(f"--- Point {idx} ---")

        user_input = input("  Enter target (x, y, z) in meters [or 'done']: ").strip()
        if user_input.lower() in ("done", "d", "quit", "q"):
            break

        try:
            parts = user_input.replace(",", " ").replace("(", "").replace(")", "").split()
            target_xyz = [float(p) for p in parts]
            if len(target_xyz) != 3:
                raise ValueError("Need exactly 3 values")
        except (ValueError, IndexError):
            print(f"  [Error] Enter 3 numbers, e.g.: 0.5 0.0 0.7")
            continue

        try:
            optitrack_pos = record_position(client, body_name, f"target ({user_input})")
        except RuntimeError as e:
            print(f"  [Error] {e}")
            continue

        target_pos = np.array(target_xyz)
        optitrack_points.append(optitrack_pos)
        target_points.append(target_pos)
        print(f"  Points recorded: {len(optitrack_points)}\n")

    if len(optitrack_points) < min_points:
        raise RuntimeError(
            f"Need at least {min_points} points, got {len(optitrack_points)}."
        )

    source = np.array(optitrack_points)
    target = np.array(target_points)
    T, rms_error = compute_rigid_transform(source, target)

    print(f"\n{'='*60}")
    print("SVD Calibration Result")
    print(f"{'='*60}")
    print(f"Points used:   {len(optitrack_points)}")
    print(f"RMS error:     {rms_error:.4f} m ({rms_error*1000:.1f} mm)")

    print(f"\nVerification:")
    for i in range(len(optitrack_points)):
        transformed = apply_transform(T, source[i])
        error = np.linalg.norm(transformed - target[i])
        print(f"  Point {i+1}: error={error*1000:.1f} mm")

    print(f"\nTransform (4×4):")
    for row in T:
        print(f"  [{row[0]:8.5f}  {row[1]:8.5f}  {row[2]:8.5f}  {row[3]:8.5f}]")

    if rms_error > 0.01:
        print(f"\n[Warning] RMS error {rms_error*1000:.1f} mm > 10 mm. "
              f"Consider re-running with more or better-measured points.")

    details = {
        "rms_error": float(rms_error),
        "num_points": len(optitrack_points),
    }
    return T, details


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Calibrate OptiTrack V120:Trio to world frame using triangular 3-ball tool"
    )
    parser.add_argument(
        "--config",
        default=os.path.join(os.path.dirname(__file__), "..", "config", "scene_config.yaml"),
    )
    parser.add_argument(
        "--output",
        default=os.path.join(os.path.dirname(__file__), "..", "config", "calibration.yaml"),
    )
    parser.add_argument(
        "--body", default=None,
        help="Rigid body name in Motive (default: first available)",
    )
    parser.add_argument(
        "--mode", choices=["frame", "svd"], default="frame",
        help="Calibration mode: 'frame' = 3-point frame definition (default), "
             "'svd' = N-point SVD registration",
    )
    parser.add_argument(
        "--table-height", type=float, default=0.0,
        help="Table height in meters. If set, the origin's Z coordinate is "
             "fixed to this value (default: 0.0 = origin is at floor level). "
             "Use e.g. --table-height 0.7 if the origin is on the table.",
    )
    parser.add_argument(
        "--min-points", type=int, default=3,
        help="Min correspondences for SVD mode (default: 3, recommended: 6+)",
    )
    args = parser.parse_args()

    # Load config and connect
    config = load_config(args.config)
    optitrack_cfg = config.get("optitrack", {})

    client = OptiTrackClient(
        server_ip=optitrack_cfg.get("server_ip", "192.168.0.101"),
        local_ip=optitrack_cfg.get("local_ip", "0.0.0.0"),
        multicast_ip=optitrack_cfg.get("multicast_ip", "239.255.42.99"),
        command_port=optitrack_cfg.get("command_port", 1510),
        data_port=optitrack_cfg.get("data_port", 1511),
    )
    client.start()
    time.sleep(1.0)

    # Find calibration body
    body_name = args.body
    if body_name is None:
        bodies = client.get_rigid_bodies()
        if not bodies:
            print("[Error] No rigid bodies detected. Is Motive streaming? "
                  "Is the calibration frame visible?")
            client.stop()
            return
        body_name = list(bodies.keys())[0]
        print(f"[Calibration] Using rigid body: '{body_name}'")
        if len(bodies) > 1:
            print(f"  Other bodies: {', '.join(bodies.keys())}")
            print(f"  Use --body <name> to select a different one.")

    # Run calibration
    try:
        if args.mode == "frame":
            T, details = calibrate_3point_frame(client, body_name, args.table_height)
        else:
            T, details = calibrate_svd(client, body_name, args.min_points)
    except RuntimeError as e:
        print(f"\n[Error] {e}")
        client.stop()
        return

    # Save
    save_calibration(args.output, T, args.mode, details)
    client.stop()

    print(f"\nCalibration complete. Saved to:")
    print(f"  {os.path.abspath(args.output)}")
    print(f"\nThis will be loaded automatically by the scene aggregator and renderer.")


if __name__ == "__main__":
    main()
