#!/usr/bin/env python3
"""
scripts/run_calibration.py — OptiTrack ↔ World Frame Calibration Tool

Interactive tool to compute the rigid transform from OptiTrack coordinates
to a desired world frame (e.g., robot base frame).

How It Works
------------
You place a tracked rigid body at multiple known positions and record
point correspondences:
  - OptiTrack reports position A for the rigid body
  - You know (or measure) the "true" position B in your desired frame

With ≥3 correspondences, SVD-based registration (Arun's method) computes
the best-fit rotation + translation mapping OptiTrack → world frame.

Usage
-----
    cd vision_engine
    python scripts/run_calibration.py

    # With custom config:
    python scripts/run_calibration.py --config config/scene_config.yaml

    # Specify which rigid body to use for calibration:
    python scripts/run_calibration.py --body calibration_wand

Procedure
---------
    1. In Motive, create a rigid body on a calibration object (e.g., marker
       on the robot end-effector or a wand you can place at known positions).

    2. Run this script. It connects to OptiTrack and prompts you to:
       a. Place the object at a known position
       b. Enter the known (x, y, z) in your target frame
       c. Press Enter to record the OptiTrack reading

    3. Repeat for ≥3 positions (6-8 recommended for accuracy).
       Choose positions spread across the workspace — not collinear.

    4. The script computes the transform and saves it to config/calibration.yaml.

Output
------
    config/calibration.yaml:
        transform: [[...], [...], [...], [...]]  # 4×4 matrix
        rms_error: 0.0032                         # meters
        num_points: 8
"""

import sys
import os
import time
import argparse
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import yaml
from cv.optitrack_client import OptiTrackClient
from cv.transforms import compute_rigid_transform


def load_config(config_path: str) -> dict:
    with open(config_path, "r") as f:
        return yaml.safe_load(f)


def save_calibration(output_path: str, transform: np.ndarray, rms_error: float, num_points: int):
    """Save calibration result to YAML."""
    data = {
        "transform": transform.tolist(),
        "rms_error": float(rms_error),
        "num_points": int(num_points),
    }
    with open(output_path, "w") as f:
        f.write("# Auto-generated by run_calibration.py\n")
        f.write("# Maps OptiTrack world coordinates → target frame coordinates\n")
        f.write(f"# RMS error: {rms_error:.4f} m ({rms_error*1000:.1f} mm)\n")
        f.write(f"# Calibrated with {num_points} point correspondences\n")
        f.write(f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        yaml.dump(data, f, default_flow_style=None)
    print(f"\n[Calibration] Saved to {output_path}")


def main():
    parser = argparse.ArgumentParser(description="OptiTrack ↔ world frame calibration")
    parser.add_argument(
        "--config",
        default=os.path.join(os.path.dirname(__file__), "..", "config", "scene_config.yaml"),
        help="Path to scene_config.yaml",
    )
    parser.add_argument(
        "--output",
        default=os.path.join(os.path.dirname(__file__), "..", "config", "calibration.yaml"),
        help="Path to save calibration.yaml",
    )
    parser.add_argument(
        "--body",
        default=None,
        help="Name of the rigid body to use for calibration (default: first available)",
    )
    parser.add_argument(
        "--min-points",
        type=int,
        default=3,
        help="Minimum correspondences required (default: 3, recommended: 6+)",
    )
    args = parser.parse_args()

    # Load config and connect
    config = load_config(args.config)
    optitrack_cfg = config.get("optitrack", {})

    client = OptiTrackClient(
        server_ip=optitrack_cfg.get("server_ip", "192.168.0.101"),
        local_ip=optitrack_cfg.get("local_ip", "0.0.0.0"),
        multicast_ip=optitrack_cfg.get("multicast_ip", "239.255.42.99"),
        command_port=optitrack_cfg.get("command_port", 1510),
        data_port=optitrack_cfg.get("data_port", 1511),
    )
    client.start()
    time.sleep(1.0)

    # Find calibration body
    body_name = args.body
    if body_name is None:
        bodies = client.get_rigid_bodies()
        if not bodies:
            print("[Error] No rigid bodies detected. Check Motive and tracking.")
            client.stop()
            return
        body_name = list(bodies.keys())[0]
        print(f"[Calibration] Using rigid body: '{body_name}'")
        if len(bodies) > 1:
            print(f"  (Other bodies available: {', '.join(bodies.keys())})")
            print(f"  Use --body <name> to select a different one.")

    print(f"""
╔══════════════════════════════════════════════════════════════════════╗
║                   OptiTrack Calibration Tool                        ║
╠══════════════════════════════════════════════════════════════════════╣
║  1. Place '{body_name}' at a known position in your target frame    ║
║  2. Enter the known (x, y, z) coordinates in meters                ║
║  3. Press Enter to record the OptiTrack reading                     ║
║  4. Repeat for at least {args.min_points} positions (6-8 recommended)            ║
║  5. Type 'done' when finished                                       ║
║                                                                      ║
║  Tips:                                                               ║
║  - Spread points across the workspace (not in a line)               ║
║  - Include points at different heights if possible                  ║
║  - Keep the rigid body visible to V120:Trio during recording         ║
╚══════════════════════════════════════════════════════════════════════╝
""")

    optitrack_points = []
    target_points = []

    while True:
        idx = len(optitrack_points) + 1
        print(f"--- Point {idx} ---")

        # Get user input for known position
        user_input = input("  Enter target (x, y, z) in meters [or 'done'/'quit']: ").strip()

        if user_input.lower() in ("done", "d", "quit", "q"):
            break

        # Parse coordinates
        try:
            parts = user_input.replace(",", " ").replace("(", "").replace(")", "").split()
            target_xyz = [float(p) for p in parts]
            if len(target_xyz) != 3:
                raise ValueError("Need exactly 3 values")
        except (ValueError, IndexError) as e:
            print(f"  [Error] Could not parse '{user_input}'. Enter 3 numbers, e.g.: 0.5 0.0 0.7")
            continue

        # Average OptiTrack readings for stability
        input("  Position the body, then press Enter to record...")

        readings = []
        print("  Recording (averaging 30 frames)...", end="", flush=True)
        for _ in range(30):
            bodies = client.get_rigid_bodies()
            if body_name in bodies and bodies[body_name].tracking_valid:
                readings.append(bodies[body_name].position.copy())
            time.sleep(0.033)  # ~30 Hz
        print(" done.")

        if len(readings) < 10:
            print(f"  [Warning] Only got {len(readings)} valid readings. "
                  "Ensure the body is visible. Try again.")
            continue

        optitrack_pos = np.mean(readings, axis=0)
        std = np.std(readings, axis=0)
        target_pos = np.array(target_xyz)

        optitrack_points.append(optitrack_pos)
        target_points.append(target_pos)

        print(f"  OptiTrack (Z-up): ({optitrack_pos[0]:.4f}, {optitrack_pos[1]:.4f}, {optitrack_pos[2]:.4f})")
        print(f"  Target:           ({target_pos[0]:.4f}, {target_pos[1]:.4f}, {target_pos[2]:.4f})")
        print(f"  Std dev:          ({std[0]:.4f}, {std[1]:.4f}, {std[2]:.4f}) m")
        print(f"  Points recorded:  {len(optitrack_points)}")
        print()

    # Compute calibration
    if len(optitrack_points) < args.min_points:
        print(f"\n[Error] Need at least {args.min_points} points, got {len(optitrack_points)}. "
              "Run again with more correspondences.")
        client.stop()
        return

    source = np.array(optitrack_points)
    target = np.array(target_points)

    T, rms_error = compute_rigid_transform(source, target)

    print(f"\n{'='*60}")
    print(f"Calibration Result")
    print(f"{'='*60}")
    print(f"Points used:   {len(optitrack_points)}")
    print(f"RMS error:     {rms_error:.4f} m ({rms_error*1000:.1f} mm)")
    print(f"\nTransform (4×4):")
    for row in T:
        print(f"  [{row[0]:8.5f}  {row[1]:8.5f}  {row[2]:8.5f}  {row[3]:8.5f}]")

    if rms_error > 0.01:
        print(f"\n[Warning] RMS error is {rms_error*1000:.1f} mm — higher than ideal (<5 mm).")
        print("  Consider re-running with more points or checking for measurement errors.")

    # Verify: show transformed OptiTrack points vs target
    print(f"\nVerification (transformed OptiTrack → target):")
    from cv.transforms import apply_transform
    for i in range(len(optitrack_points)):
        transformed = apply_transform(T, source[i])
        error = np.linalg.norm(transformed - target[i])
        print(f"  Point {i+1}: "
              f"transformed=({transformed[0]:.4f}, {transformed[1]:.4f}, {transformed[2]:.4f})  "
              f"target=({target[i][0]:.4f}, {target[i][1]:.4f}, {target[i][2]:.4f})  "
              f"error={error*1000:.1f} mm")

    # Save
    save_calibration(args.output, T, rms_error, len(optitrack_points))
    client.stop()

    print(f"\nCalibration complete. The transform has been saved to:")
    print(f"  {os.path.abspath(args.output)}")
    print(f"\nThis transform will be automatically loaded by the scene aggregator.")


if __name__ == "__main__":
    main()
